@startuml
skinparam linetype ortho

package "moduloInicio" {
  [Inicio] as home
}

package "moduloRit" {
  [Actividades Económicas] as actividades
  [Establecimiento dinámico] as est_din
}

home --> actividades : ir a RIT
actividades --> est_din : seleccionar establecimiento dinámico
@enduml