@startuml registroUsuario
package registroUsuario {
  component registroUsuarioExitosoV2 as [registroUsuarioExitosoV2.xhtml]
  component registroUsuarioValidaDocumentoV2 as [registroUsuarioValidaDocumentoV2.xhtml]

  [registroUsuarioExitosoV2.xhtml] --> registroUsuarioBean : confirmar()
  [registroUsuarioValidaDocumentoV2.xhtml] --> registroUsuarioBean : validarDocumento()
}
@enduml