@startuml
top to bottom direction

title Diagrama de Navegación PrettyFaces - pretty-config.xml

(*) --> "Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']} => (/site/acuerdoFirmaElectronica/advertencia.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)"
"//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)" --> "//acuerdoFirmaElectronica/bloqueo/#{ !acuerdoFirmaElectronicaBean.tercvali } => (/site/acuerdoFirmaElectronica/bloqueo.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)"
"//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)" --> "//acuerdoFirmaElectronica/codigoSeguridad/#{titles['pagina.acuerdofirma.paso3']} => (/site/acuerdoFirmaElectronica/codigoSeguridad.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)"
"//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)" --> "//acuerdoFirmaElectronica/descargaArchivo/#{titles['pagina.acuerdofirma.paso4']} => (/site/acuerdoFirmaElectronica/descargaArchivo.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)"
"//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)" --> "//acuerdoFirmaElectronica/informacionTercero/#{titles['pagina.acuerdofirma.paso2']} => (/site/acuerdoFirmaElectronica/informacionTercero.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)"
"//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)" --> "//acuerdoFirmaElectronica/modalError/#{acuerdoFirmaElectronicaBean.texterro} => (/site/acuerdoFirmaElectronica/modalError.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)"
"//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)" --> "//acuerdoFirmaElectronica/terminosCondiciones/#{titles['pagina.acuerdofirma.paso1']} => (/site/acuerdoFirmaElectronica/terminosCondiciones.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)"
"//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)" --> "//acuerdoFirmaElectronica/#{appConfigMB.plantilla} => (/site/acuerdoFirmaElectronica.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//acuerdoPago/#{appConfigMB.plantilla} => (/site/acuerdoPago.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//cambioClaveValorizacion/#{appConfigMB.plantilla} => (/site/cambioClaveValorizacion.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//censoValorizacion/modalAnexosFodecamp/#{censoValorizacionBean.fodecampSeleccionado.focaanex} => (/site/censoValorizacion/modalAnexosFodecamp.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//censoValorizacion/modalAnexosFodecampPredio/#{censoValorizacionPrediosBean.fodecampSeleccionado.focaanex} => (/site/censoValorizacion/modalAnexosFodecampPredio.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//censoValorizacion/modalFocaobse/#{censoValorizacionBean.fodecampSeleccionado.focaetiq} => (/site/censoValorizacion/modalFocaobse.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//censoValorizacion/modalFocaobsePredio/#{censoValorizacionPrediosBean.fodecampSeleccionado.focaetiq} => (/site/censoValorizacion/modalFocaobsePredio.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//censoValorizacion/modalLiquidacionPreliminar/#{ censoValorizacionPrediosBean.detalleLiquidacion.get(0) } => (/site/censoValorizacion/modalLiquidacionPreliminar.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//censoValorizacion/#{censoValorizacionBean.cargaPreRender('')} => (/site/censoValorizacion.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//certificadoCierreEstablecimiento/certificadoCierreEstablecimiento/#{appConfigMB.plantilla} => (/site/certificadoCierreEstablecimiento/certificadoCierreEstablecimiento.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//certificadoCierreEstablecimiento/tablaHistoricoCertCierre/#{(certificadoCierreEstablecimientoBean.listDocuadmiM.size() == 0 ? false : true)} => (/site/certificadoCierreEstablecimiento/tablaHistoricoCertCierre.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//certificadoPazySalvo/#{appConfigMB.plantilla} => (/site/certificadoPazySalvo.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//certificadoPazySalvoValorizacion/#{titles['page.certificado.titulo']} => (/site/certificadoPazySalvoValorizacion.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//confirmarPago/#{appConfigMB.plantilla} => (/site/confirmarPago.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//delineacionUrbana/#{appConfigMB.plantilla} => (/site/delineacionUrbana.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//descargaArchivos/#{appConfigMB.plantilla} => (/site/descargaArchivos.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//detalleFirmantes/#{detalleFirmantesBean.cargaPreRender(idForm,idModal)} => (/site/detalleFirmantes.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//diligenciamiento/actividadesEconomicas/#{actividadesEconomicasBean.cargaPreRender(idForm)} => (/site/diligenciamiento/actividadesEconomicas.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//diligenciamiento/presentaDeclaracionV2/#{presentaDeclaracionV2Bean.cargaPreRender(idForm,idModal)} => (/site/diligenciamiento/presentaDeclaracionV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//diligenciamiento/renglonesDiliV2/#{renglonesDiliV2Bean.cargaPreRender(idForm,idSeccion,idBodyModal)} => (/site/diligenciamiento/renglonesDiliV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//diligenciamiento/tablaRepresentantes/#{tablaRepresentantesBean.cargaPreRender(idForm)} => (/site/diligenciamiento/tablaRepresentantes.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//diligencieDeclaracionV2/#{appConfigMB.plantilla} => (/site/diligencieDeclaracionV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//encabezadoFormularioDeclaracionV2/#{encabezadoFormularioDeclaracionV2.cargaPreRender(idForm)} => (/site/encabezadoFormularioDeclaracionV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//estadoCuentaValorizacion/#{appConfigMB.plantilla} => (/site/estadoCuentaValorizacion.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//estadoSolicitudBomberos/modalOpcionesDePago/#{labels['pagina.facturaexpress.listOppa']} => (/site/estadoSolicitudBomberos/modalOpcionesDePago.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//estadoSolicitudBomberos/modalTablaSolicitudes/#{tablaSolicitudesBean.mensajeAlertaModal} => (/site/estadoSolicitudBomberos/modalTablaSolicitudes.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//estadoSolicitudBomberos/modalTablaSolicitudesBoton/#{tablaSolicitudesBean.mensajeAlertaModal} => (/site/estadoSolicitudBomberos/modalTablaSolicitudesBoton.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//estadoSolicitudBomberos/#{appConfigMB.plantilla} => (/site/estadoSolicitudBomberos.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//facturaDelineacion/#{appConfigMB.plantilla} => (/site/facturaDelineacion.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//facturaExpres/#{appConfigMB.plantilla} => (/site/facturaExpres.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//facturaExpresV2/#{titles['page.facturaexpres.title1']} => (/site/facturaExpresV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//facturaExpresValorizacion/#{titles['page.facturaexpres.title1']} => (/site/facturaExpresValorizacion.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//firmaDeclaracion/contenidoEnviaCodigo/#{labels['pagina.firmelec.texto1']} => (/site/firmaDeclaracion/contenidoEnviaCodigo.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//firmaDeclaracion/contenidoIdFirma/#{firmaDeclaracionBean.idfirma != null} => (/site/firmaDeclaracion/contenidoIdFirma.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//firmaDeclaracion/modalFirmar/#{labels['pagina.firmelec.codivali.texto']} => (/site/firmaDeclaracion/modalFirmar.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//firmaDeclaracion/modalFormularioCodivali/#{labels['pagina.firmelec.modal.texto']} => (/site/firmaDeclaracion/modalFormularioCodivali.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//firmaDeclaracion/modalInfoInicial/#{ (firmaDeclaracionBean.valifechvenci or properties['valida.fechavencimiento'] eq 'N') and !firmaDeclaracionBean.valiclasterc  } => (/site/firmaDeclaracion/modalInfoInicial.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//firmaDeclaracion/modalPresentarDecl/#{labels['pagina.presdecl.titulo']} => (/site/firmaDeclaracion/modalPresentarDecl.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//firmaDeclaracion/#{appConfigMB.plantilla} => (/site/firmaDeclaracion.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//formPredioVisorGeografico/#{request.contextPath} => (/site/formPredioVisorGeografico.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//formularioBomberos/modalFormBomberos/#{formularioBomberosBean.mensajeAlertaModal} => (/site/formularioBomberos/modalFormBomberos.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//formularioBomberos/modalFormCamposFaltantes/#{formularioBomberosBean.mensajeAlertaModal} => (/site/formularioBomberos/modalFormCamposFaltantes.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//formularioBomberos/#{appConfigMB.plantilla} => (/site/formularioBomberos.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//formularioDeclaracionV2/#{appConfigMB.plantilla} => (/site/formularioDeclaracionV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//formularioPago/#{appConfigMB.plantilla} => (/site/formularioPago.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//formularioRepresentante/#{formularioRepresentanteBean.cargaPreRender(idForm)} => (/site/formularioRepresentante.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//formulariosPago/camposEcollect/#{formularioPagoBean.campospago.tidodesc} => (/site/formulariosPago/camposEcollect.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//formulariosPago/camposPayulatam/#{request.contextPath} => (/site/formulariosPago/camposPayulatam.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//formulariosPago/resumenEcollect/#{resumenPagoBean.campospago.estado} => (/site/formulariosPago/resumenEcollect.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//formulariosPago/resumenPagoPayulatam/#{resumenPagoBean.obtenerValor('reference_pol')} => (/site/formulariosPago/resumenPagoPayulatam.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//gestionFirmantes/formularioRepresentante/#{gestionFirmantesBean.tercreprselectinfo.terccodi} => (/site/gestionFirmantes/formularioRepresentante.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//gestionFirmantes/modalConfirmacion/#{gestionFirmantesBean.actualizarTercrepr()} => (/site/gestionFirmantes/modalConfirmacion.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//gestionFirmantes/#{appConfigMB.plantilla} => (/site/gestionFirmantes.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//habilitaFirmantes/advertencia/#{labels['pagina.habifirm.alerta']} => (/site/habilitaFirmantes/advertencia.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//habilitaFirmantes/bloqueo/#{ !habilitaFirmantesBean.termproc                                            and !habilitaFirmantesBean.tercvali                                            and !(habilitaFirmantesBean.getValidacionRIT() eq 'B')} => (/site/habilitaFirmantes/bloqueo.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//habilitaFirmantes/cancelaproceso/#{titles['pagina.habilitaFirmantes.cancproc']} => (/site/habilitaFirmantes/cancelaproceso.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//habilitaFirmantes/codigoSeguridad/#{titles['pagina.habilitaFirmantes.paso3']} => (/site/habilitaFirmantes/codigoSeguridad.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//habilitaFirmantes/documentosAnexos/#{titles['pagina.habilitaFirmantes.paso5']} => (/site/habilitaFirmantes/documentosAnexos.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//habilitaFirmantes/infoFirmantes/#{titles['pagina.habilitaFirmantes.paso4']} => (/site/habilitaFirmantes/infoFirmantes.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//habilitaFirmantes/modalError/#{habilitaFirmantesBean.texterro} => (/site/habilitaFirmantes/modalError.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//habilitaFirmantes/preguntasSeguridad/#{titles['pagina.habilitaFirmantes.paso2']} => (/site/habilitaFirmantes/preguntasSeguridad.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//habilitaFirmantes/terminaproceso/#{titles['pagina.habilitaFirmantes.termproc']} => (/site/habilitaFirmantes/terminaproceso.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//habilitaFirmantes/terminosCondiciones/#{titles['pagina.habilitaFirmantes.paso1']} => (/site/habilitaFirmantes/terminosCondiciones.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//habilitaFirmantes/#{habilitaFirmantesBean.tercvali and !(habilitaFirmantesBean.getValidacionRIT() eq 'B')} => (/site/habilitaFirmantes.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//home/#{request.contextPath} => (/site/home.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/detalleFirmantes/#{detalleFirmantesBean.cargaPreRender(idForm,idModal)} => (/site/informacionExogena/detalleFirmantes.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalArchivoMost/#{informacionExogenaBean.conteo.intValue()} => (/site/informacionExogena/modalArchivoMost.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalArchivoMostac/#{informacionExogenaBean.conteo.intValue()} => (/site/informacionExogena/modalArchivoMostac.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalBorrar/#{informacionExogenaBean.borrarRegistro2()} => (/site/informacionExogena/modalBorrar.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalConfirm1/#{labels['pagina.infoExog.confirmar']} => (/site/informacionExogena/modalConfirm1.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalConfirm2/#{labels['pagina.infoExog.confirmar']} => (/site/informacionExogena/modalConfirm2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalConfirm3/#{labels['pagina.infoExog.confirmar']} => (/site/informacionExogena/modalConfirm3.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalDatatableArchivos/#{informacionExogenaBean.gestArchListM} => (/site/informacionExogena/modalDatatableArchivos.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalDatatableNota/#{informacionExogenaBean.periodo} => (/site/informacionExogena/modalDatatableNota.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalDatatableNota2/#{labels['pagina.infoExog.mens3soacha']} => (/site/informacionExogena/modalDatatableNota2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalDetalleFirmaExog/#{labels['pagina.infoExog.mens3soacha']} => (/site/informacionExogena/modalDetalleFirmaExog.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalErrores/#{informacionExogenaBean.mensaje} => (/site/informacionExogena/modalErrores.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalErrorProces/#{informacionExogenaBean.conteo.intValue()} => (/site/informacionExogena/modalErrorProces.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalFileUpload/#{informacionExogenaBean.msgModal} => (/site/informacionExogena/modalFileUpload.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalPresentar/#{labels['pagina.infoExog.confirmar']} => (/site/informacionExogena/modalPresentar.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalPresentarExog/#{informacionExogenaBean.presentarInfoExog()} => (/site/informacionExogena/modalPresentarExog.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalProcesoEx/#{informacionExogenaBean.msgExito} => (/site/informacionExogena/modalProcesoEx.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/modalProcesoFinalizado/#{informacionExogenaBean.diffHours} => (/site/informacionExogena/modalProcesoFinalizado.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/tabCargar/#{titles['pagina.infoexog.text2']} => (/site/informacionExogena/tabCargar.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/tabConsultaHistorica/#{titles['pagina.infoExog.paso4']} => (/site/informacionExogena/tabConsultaHistorica.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/tabDescargaDiligencia/#{titles['pagina.infoexog.text1']} => (/site/informacionExogena/tabDescargaDiligencia.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/tabValidaCorrige/#{titles['pagina.infoexog.text3']} => (/site/informacionExogena/tabValidaCorrige.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogena/#{appConfigMB.plantilla} => (/site/informacionExogena.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//informacionExogenaTemp/#{appConfigMB.plantilla} => (/site/informacionExogenaTemp.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//listaCertificado/#{certificadoPazySalvoValorizacionBean.listpasysalvo} => (/site/listaCertificado.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//loadPage/#{request.contextPath} => (/site/loadPage.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//notificaciones/#{appConfigMB.plantilla} => (/site/notificaciones.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//opcionesModuloBomberos/#{appConfigMB.plantilla} => (/site/opcionesModuloBomberos.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//otrasDeclaraciones/#{appConfigMB.plantilla} => (/site/otrasDeclaraciones.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//pdfPreview/#{sessionUsuarioMB.borrarRutaPDF()} => (/site/pdfPreview.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//perfilFirmante/#{appConfigMB.plantilla} => (/site/perfilFirmante.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//perfilUsuarioValorizacion/#{appConfigMB.plantilla} => (/site/perfilUsuarioValorizacion.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//preguntasSeguridadRegistroUsuarioV2/#{registroUsuarioV2Bean.mensajeRespuestasInvalidas} => (/site/preguntasSeguridadRegistroUsuarioV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//recordarContrasenaV2/#{appConfigMB.plantilla} => (/site/recordarContrasenaV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//recordarContrasenaValorizacion/#{titles['pagina.recordarcontrasena.title1']} => (/site/recordarContrasenaValorizacion.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//registroUsuarioBienvenidoV2/#{appConfigMB.plantilla} => (/site/registroUsuarioBienvenidoV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//registroUsuarioExitosoV2/#{appConfigMB.plantilla} => (/site/registroUsuarioExitosoV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//registroUsuarioV2/#{appConfigMB.plantilla} => (/site/registroUsuarioV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//registroUsuarioValidaDocumentoV2/#{appConfigMB.plantilla} => (/site/registroUsuarioValidaDocumentoV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//resumenPago/#{appConfigMB.plantilla} => (/site/resumenPago.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/actividadesEconomicasRit/#{actividadesEconomicasRitBean.preRender(subseccion)} => (/site/rit/actividadesEconomicasRit.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/actividadesEstablecimiento/#{registrarEstablecimientoBean.preRender(subseccion)} => (/site/rit/actividadesEstablecimiento.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/anexos/#{anexoBean.preRender(subseccion)} => (/site/rit/anexos.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/cerrarEstablecimientos/#{cerrarEstablecimientosBean.preRender(subseccion)} => (/site/rit/cerrarEstablecimientos.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/consultarRit/#{appConfigMB.plantilla} => (/site/rit/consultarRit.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/establecimientos/#{establecimientosBean.preRender(subseccion)} => (/site/rit/establecimientos.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/informacionContribuyente/#{informacionContribuyenteBean.preRender(idForm,idFormTabView,idParcialPanelSubmit,subseccion)} => (/site/rit/informacionContribuyente.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/informacionContribuyenteComercial/#{informacionContribuyenteComercialBean.preRender(subseccion)} => (/site/rit/informacionContribuyenteComercial.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/loginRitApertura/#{appConfigMB.plantilla} => (/site/rit/loginRitApertura.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/loginRitNovedad/#{appConfigMB.plantilla} => (/site/rit/loginRitNovedad.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/registrarEstablecimiento/#{registrarEstablecimientoBean.preRender(subseccion)} => (/site/rit/registrarEstablecimiento.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/representantes/#{representantesBean.preRender(subseccion)} => (/site/rit/representantes.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/responsabilidadTributaria/#{responsabilidadTributariaBean.preRender(idForm,idFormTabView,idFormPanelSeccion,subseccion)} => (/site/rit/responsabilidadTributaria.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/tablaRitGuardado/#{loginRitNovedadBean.preRender()} => (/site/rit/tablaRitGuardado.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/terminosCondiciones/#{informacionContribuyenteBean.boTerminosCondiciones} => (/site/rit/terminosCondiciones.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/ubicacionContacto/#{ubicacionContactoBean.preRender(subseccion)} => (/site/rit/ubicacionContacto.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//rit/#{appConfigMB.plantilla} => (/site/rit.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//solicitudPropietarioPredio/#{solicitudPropietarioPredioBean.cargaPreRender('')} => (/site/solicitudPropietarioPredio.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//solicitudPropietarioPredioAnexos/#{solicitudPropietarioPredioAnexosBean.titulo} => (/site/solicitudPropietarioPredioAnexos.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//tablaFormularioGuardadoV2/#{tablaFormularioGuardadoV2.cargaPreRender(idForm)} => (/site/tablaFormularioGuardadoV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//tablaListadoDeolestaV2/#{tablaListadoDeolestaV2Bean.cargaPreRender(idForm)} => (/site/tablaListadoDeolestaV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//tablaSolicitudes/#{tablaSolicitudesBean.cargaPreRender(idForm)} => (/site/tablaSolicitudes.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//usuarioFirmaElectronica/#{appConfigMB.plantilla} => (/site/usuarioFirmaElectronica.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//valiCertificadosBomberos/listaCertificadoBomberos/#{valiCertificadosBomberosBean.tipoImpuesto} => (/site/valiCertificadosBomberos/listaCertificadoBomberos.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//valiCertificadosBomberos/modalCertificadosBomberosValido/#{labels['pagina.general.aceptar']} => (/site/valiCertificadosBomberos/modalCertificadosBomberosValido.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//valiCertificadosBomberos/#{appConfigMB.plantilla} => (/site/valiCertificadosBomberos.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//valiCertificadosCierre/listaCertificadoCierre/#{valiCertificadosCierreBean.tipoImpuesto} => (/site/valiCertificadosCierre/listaCertificadoCierre.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//valiCertificadosCierre/modalCertificadosCierreValido/#{labels['pagina.general.aceptar']} => (/site/valiCertificadosCierre/modalCertificadosCierreValido.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//valiCertificadosCierre/#{appConfigMB.plantilla} => (/site/valiCertificadosCierre.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//validacionPazySalvoV2/modalCertificado/#{validacionPazySalvoV2Bean.certificado.tiimdesc} => (/site/validacionPazySalvoV2/modalCertificado.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//validacionPazySalvoV2/modalCertificadoInvias/#{validacionPazySalvoV2Bean.certificado.certcataPK.cecanume} => (/site/validacionPazySalvoV2/modalCertificadoInvias.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//validacionPazySalvoV2/modalQr/#{titles['page.validacertificado.modal.texto']} => (/site/validacionPazySalvoV2/modalQr.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//validacionPazySalvoV2/#{appConfigMB.plantilla} => (/site/validacionPazySalvoV2.xhtml)"
"Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)" --> "//visorGeograficoInvias/#{request.contextPath} => (/site/visorGeograficoInvias.xhtml)"
"//loginV2/#{appConfigMB.plantilla} => (/site/loginV2.xhtml)" --> "Inicio (//acuerdoFirmaElectronica/advertencia/#{labels['pagina.acuerdofirma.alerta2']}) => (/site/acuerdoFirmaElectronica/advertencia.xhtml)"

@enduml